env_list = ["format", "3.11"]

[env.format]
deps = ["black==22.3.0"]
skip_install = true
commands = [
  ["black", "."]
]

[env."3.11"]
deps = [
  "-rrequirements.txt",
]
commands = [
  "python -m unittest tests/unit/test_diffusion2d_functions.py && python -m pytest tests/integration/test_diffusion2d.py {posargs}"
]

